Improve nut agent plugin with verbose output

diff --git a/usr/lib/check_mk_agent/plugin/nut b/usr/lib/check_mk_agent/plugin/nut
--- a/usr/lib/check_mk_agent/plugin/nut
+++ b/usr/lib/check_mk_agent/plugin/nut
@@ -1,9 +1,12 @@
 #!/bin/sh
 
+echo '<<<nut>>>'
+
 if which upsc > /dev/null 2>&1 ; then
-    echo '<<<nut>>>'
-    for ups in $(upsc -l 2>/dev/null)
+    for ups in $(upsc -l > /dev/stdout 2> /dev/null)
     do
-	    upsc $ups| sed "s,^,$ups ,"
+        upsc $ups > /dev/stdout 2> /dev/null | sed "s,^,$ups ,"
     done
+else
+    echo "ERROR: upsc not found" >&2
 fi
